# Generated by Django 2.1.2 on 2018-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_auto_20181010_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario_mensual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
