# Generated by Django 2.1.2 on 2018-10-07 17:52

import candidates.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=11, validators=[candidates.validators.validar_cedula])),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('salario_aspira', models.IntegerField(blank=True)),
                ('capacitaciones', models.ManyToManyField(blank=True, to='human_resources.Capacitacion')),
                ('competencias', models.ManyToManyField(blank=True, to='human_resources.Competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('salario', models.IntegerField()),
                ('puesto_ocupado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Puesto')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='experiencias',
            field=models.ManyToManyField(blank=True, to='candidates.Experiencia'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Puesto'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='recomendado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Empleado'),
        ),
    ]
