# Generated by Django 2.1.2 on 2018-10-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20181010_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='esta_reclutado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
